### ISSUE TITLE
could you also wrap samtools or htslib into  julia lang ?

### ISSUE THREAD

**Issue by SeqCrafter** [jonathanBieler/BurrowsWheelerAligner.jl#4]
I see a gen dir in your project, and maybe you use clang.jl to automatically build some Julia library from bwa_jll. It's a good idea to build samtools or htslib because XAM.jl uses pure Julia to parse BAM files so that it lost some functions such as `pileup`. 

I also want to do that, but I know a little about C.

**Comment by jonathanBieler** [comment]
Hey, in theory it's possible, it's actually been done already :

https://github.com/bicycle1885/HTSLib.jl

But it's probably not the best idea (project seems abandoned), it's usually better to do things in Julia. Even for BWA I think a Julia implementation would be nice to have. For pileups one could relatively easily do this in Julia, I could give you a head start if you want.

In any case it's not really related to this package, so I'm closing this for now.
