### ISSUE TITLE
Compatibility for XAM should be changed

### ISSUE THREAD

**Issue by mashu** [jonathanBieler/BurrowsWheelerAligner.jl#6]
Hi,

3 days ago XAM 0.4.x was released, finally using latest Automa 1.x so things are not breaking, but this package has compat 0.3.x XAM, do you think it could be updated ? I think API didn't change.

**Comment by jonathanBieler** [comment]
Let's see if it passes : 

https://github.com/jonathanBieler/BurrowsWheelerAligner.jl/actions/runs/7714031511

**Comment by mashu** [comment]
Seems to be building, nice!

**Comment by jonathanBieler** [comment]
I'll make a release, but you can user #main for now.
